Delete author
Thiago-Alexandre/Produtos_Relatorios pull request #47
Opened 2021-05-17 19:00 UTC by LucasQuinotto

2021-05-17 19:03 UTC, bublitzjr requested changes

2021-05-17 19:03 UTC, bublitzjr commented on API_Products/database/book_db.py
> +<<<<<<< HEAD
Favor resolver confltos

2021-05-17 19:41 UTC, bublitzjr approved these changes
ok

2021-05-17 19:56 UTC, Thiago-Alexandre approved these changes
Ok

2021-05-18 11:10 UTC, Vergiliogu requested changes
Dar pull com a develop

2021-05-18 11:28 UTC, Vergiliogu requested changes

2021-05-18 11:28 UTC, Vergiliogu commented on API_Products/controllers/author_controller.py
> +            raise Exception("A autor já está sendo utilizado, não é possível deletá-lo agora.")
A autor?

2021-05-18 11:28 UTC, Vergiliogu commented on API_Products/database/author_db.py
> +        raise Exception("Nenhum editor encontrado!")
Editor?

2021-05-18 11:36 UTC, Vergiliogu approved these changes

2021-05-18 11:37 UTC, merged