New cluster connection
Thiago-Alexandre/Produtos_Relatorios pull request #72
Opened 2021-05-25 18:00 UTC by Thiago-Alexandre

2021-05-25 18:27 UTC, gabicristofolini approved these changes

2021-05-26 11:09 UTC, carloseduribeiro approved these changes

2021-05-26 11:10 UTC, carloseduribeiro reviewed
Essas alterações não são necessárias, é só alterar o valor nas variáveis já existentes no arquivo auth.py

2021-05-26 11:11 UTC, carloseduribeiro requested changes
Essas alterações não são necessárias, é só alterar o valor nas variáveis já existentes no arquivo auth.py

2021-05-26 11:58 UTC, closed without merging